// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class BaiGiang
{
    [Key]
    public int MaBaiGiang { get; set; }

    public int? MaDanhMuc { get; set; }

    public int? CapDo { get; set; }

    [Required]
    [StringLength(128)]
    public string TieuDe { get; set; }

    public int? MaPart { get; set; }

    [StringLength(512)]
    public string NoiDungTomTat { get; set; }

    public string NoiDung { get; set; }

    public int? MaAdminNoiDung { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayTao { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [InverseProperty("MaBaiGiangNavigation")]
    public virtual ICollection<BuocLoTrinh> BuocLoTrinh { get; set; } = new List<BuocLoTrinh>();

    [ForeignKey("MaAdminNoiDung")]
    [InverseProperty("BaiGiang")]
    public virtual NguoiDung MaAdminNoiDungNavigation { get; set; }

    [ForeignKey("MaDanhMuc")]
    [InverseProperty("BaiGiang")]
    public virtual DanhMucBaiGiang MaDanhMucNavigation { get; set; }

    [ForeignKey("MaPart")]
    [InverseProperty("BaiGiang")]
    public virtual PartTOEIC MaPartNavigation { get; set; }

    [InverseProperty("MaBaiGiangNavigation")]
    public virtual ICollection<TaiNguyenBaiGiang> TaiNguyenBaiGiang { get; set; } = new List<TaiNguyenBaiGiang>();
}