// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaLesson", "ThuTu", Name = "UQ_BuocLoTrinh_ThuTu", IsUnique = true)]
public partial class BuocLoTrinh
{
    [Key]
    public int MaBuoc { get; set; }

    public int MaLesson { get; set; }

    [Required]
    [StringLength(128)]
    public string TieuDe { get; set; }

    public int ThuTu { get; set; }

    public int? MaBaiGiang { get; set; }

    public int? MaDeThi { get; set; }

    public int? MaChuDe { get; set; }

    [ForeignKey("MaBaiGiang")]
    [InverseProperty("BuocLoTrinh")]
    public virtual BaiGiang MaBaiGiangNavigation { get; set; }

    [ForeignKey("MaChuDe")]
    [InverseProperty("BuocLoTrinh")]
    public virtual ChuDe MaChuDeNavigation { get; set; }

    [ForeignKey("MaDeThi")]
    [InverseProperty("BuocLoTrinh")]
    public virtual DeThi MaDeThiNavigation { get; set; }

    [ForeignKey("MaLesson")]
    [InverseProperty("BuocLoTrinh")]
    public virtual LessonKhoaHoc MaLessonNavigation { get; set; }

    [InverseProperty("MaBuocNavigation")]
    public virtual ICollection<TienDoBuocLoTrinh> TienDoBuocLoTrinh { get; set; } = new List<TienDoBuocLoTrinh>();
}