// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaKetQua", "ThuTu", Name = "UQ_CauHoiLuotLam_ThuTu", IsUnique = true)]
[Index("MaKetQua", "MaPart", "ThuTuTrongPart", Name = "UQ_CauHoiLuotLam_ThuTuTrongPart", IsUnique = true)]
public partial class CauHoiLuotLam
{
    [Key]
    public int MaCauHoiLuotLam { get; set; }

    public int MaKetQua { get; set; }

    public int? MaNhomLuotLam { get; set; }

    public int? MaCauHoiGoc { get; set; }

    public int MaPart { get; set; }

    public int ThuTu { get; set; }

    public int ThuTuTrongPart { get; set; }

    public string NoiDung { get; set; }

    [Required]
    [StringLength(512)]
    public string PhuongAnA { get; set; }

    [Required]
    [StringLength(512)]
    public string PhuongAnB { get; set; }

    [Required]
    [StringLength(512)]
    public string PhuongAnC { get; set; }

    [StringLength(512)]
    public string PhuongAnD { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string PhuongAnDung { get; set; }

    public string GiaiThich { get; set; }

    [InverseProperty("MaCauHoiLuotLamNavigation")]
    public virtual ChiTietKetQua ChiTietKetQua { get; set; }

    [ForeignKey("MaCauHoiGoc")]
    [InverseProperty("CauHoiLuotLam")]
    public virtual CauHoi MaCauHoiGocNavigation { get; set; }

    [ForeignKey("MaKetQua")]
    [InverseProperty("CauHoiLuotLam")]
    public virtual KetQuaLamBai MaKetQuaNavigation { get; set; }

    [ForeignKey("MaNhomLuotLam")]
    [InverseProperty("CauHoiLuotLam")]
    public virtual NhomLuotLam MaNhomLuotLamNavigation { get; set; }

    [ForeignKey("MaPart")]
    [InverseProperty("CauHoiLuotLam")]
    public virtual PartTOEIC MaPartNavigation { get; set; }
}