// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class CauHoi
{
    [Key]
    public int MaCauHoi { get; set; }

    public string NoiDung { get; set; }

    [Required]
    [StringLength(512)]
    public string PhuongAnA { get; set; }

    [Required]
    [StringLength(512)]
    public string PhuongAnB { get; set; }

    [Required]
    [StringLength(512)]
    public string PhuongAnC { get; set; }

    [StringLength(512)]
    public string PhuongAnD { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string PhuongAnDung { get; set; }

    public string GiaiThich { get; set; }

    public int MaPart { get; set; }

    public byte DoKho { get; set; }

    [InverseProperty("MaCauHoiNavigation")]
    public virtual ICollection<CauHoiDeThi> CauHoiDeThi { get; set; } = new List<CauHoiDeThi>();

    [ForeignKey("MaPart")]
    [InverseProperty("CauHoi")]
    public virtual PartTOEIC MaPartNavigation { get; set; }

    [InverseProperty("MaCauHoiNavigation")]
    public virtual NhomCauHoi NhomCauHoi { get; set; }

    [ForeignKey("MaCauHoi")]
    [InverseProperty("MaCauHoi")]
    public virtual ICollection<PhanLoaiCauHoi> MaPhanLoai { get; set; } = new List<PhanLoaiCauHoi>();
}