// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[PrimaryKey("MaDeThi", "MaCauHoi")]
[Index("MaDeThi", "ThuTu", Name = "UQ_CauHoiDeThi_ThuTu", IsUnique = true)]
public partial class CauHoiDeThi
{
    [Key]
    public int MaDeThi { get; set; }

    [Key]
    public int MaCauHoi { get; set; }

    public int ThuTu { get; set; }

    [InverseProperty("CauHoiDeThi")]
    public virtual ICollection<ChiTietKetQua> ChiTietKetQua { get; set; } = new List<ChiTietKetQua>();

    [ForeignKey("MaCauHoi")]
    [InverseProperty("CauHoiDeThi")]
    public virtual CauHoi MaCauHoiNavigation { get; set; }

    [ForeignKey("MaDeThi")]
    [InverseProperty("CauHoiDeThi")]
    public virtual DeThi MaDeThiNavigation { get; set; }
}