// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class ChiTietKetQua
{
    [Key]
    public int MaCauHoiLuotLam { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string DapAnChon { get; set; }

    public bool DanhDau { get; set; }

    [ForeignKey("MaCauHoiLuotLam")]
    [InverseProperty("ChiTietKetQua")]
    public virtual CauHoiLuotLam MaCauHoiLuotLamNavigation { get; set; }
}