// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[PrimaryKey("MaLanLuyen", "MaTuVung")]
[Index("MaLanLuyen", "ThuTu", Name = "UQ_ChiTietLuyenTuVung_ThuTu", IsUnique = true)]
public partial class ChiTietLuyenTuVung
{
    [Key]
    public int MaLanLuyen { get; set; }

    public int MaChuDe { get; set; }

    [Key]
    public int MaTuVung { get; set; }

    public int ThuTu { get; set; }

    [Required]
    [StringLength(512)]
    public string NoiDungCauHoi { get; set; }

    [Required]
    [StringLength(256)]
    public string PhuongAnA { get; set; }

    [Required]
    [StringLength(256)]
    public string PhuongAnB { get; set; }

    [Required]
    [StringLength(256)]
    public string PhuongAnC { get; set; }

    [Required]
    [StringLength(256)]
    public string PhuongAnD { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string PhuongAnDung { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string DapAnChon { get; set; }

    public bool? LaDung { get; set; }

    [ForeignKey("MaLanLuyen, MaChuDe")]
    [InverseProperty("ChiTietLuyenTuVung")]
    public virtual LanLuyenTuVung LanLuyenTuVung { get; set; }

    [ForeignKey("MaChuDe, MaTuVung")]
    [InverseProperty("ChiTietLuyenTuVung")]
    public virtual TuVungChuDe TuVungChuDe { get; set; }
}