// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[PrimaryKey("MaKetQua", "MaCauHoi")]
public partial class ChiTietKetQua
{
    [Key]
    public int MaKetQua { get; set; }

    public int MaDeThi { get; set; }

    [Key]
    public int MaCauHoi { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string DapAnChon { get; set; }

    public bool? LaDung { get; set; }

    public bool DanhDau { get; set; }

    [ForeignKey("MaDeThi, MaCauHoi")]
    [InverseProperty("ChiTietKetQua")]
    public virtual CauHoiDeThi CauHoiDeThi { get; set; }

    [ForeignKey("MaKetQua, MaDeThi")]
    [InverseProperty("ChiTietKetQua")]
    public virtual KetQuaLamBai KetQuaLamBai { get; set; }
}