// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[PrimaryKey("MaSinhDe", "MaPart")]
public partial class ChiTietCauHinhDeThi
{
    [Key]
    public int MaSinhDe { get; set; }

    [Key]
    public int MaPart { get; set; }

    public int SoCauDe { get; set; }

    public int SoCauTB { get; set; }

    public int SoCauKho { get; set; }

    [ForeignKey("MaPart")]
    [InverseProperty("ChiTietCauHinhDeThi")]
    public virtual PartTOEIC MaPartNavigation { get; set; }

    [ForeignKey("MaSinhDe")]
    [InverseProperty("ChiTietCauHinhDeThi")]
    public virtual ThongTinSinhDe MaSinhDeNavigation { get; set; }
}