// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class ChuDe
{
    [Key]
    public int MaChuDe { get; set; }

    [Required]
    [StringLength(128)]
    public string TenChuDe { get; set; }

    [StringLength(256)]
    public string MoTa { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [InverseProperty("MaChuDeNavigation")]
    public virtual ICollection<BuocLoTrinh> BuocLoTrinh { get; set; } = new List<BuocLoTrinh>();

    [InverseProperty("MaChuDeNavigation")]
    public virtual ICollection<LanLuyenTuVung> LanLuyenTuVung { get; set; } = new List<LanLuyenTuVung>();

    [InverseProperty("MaChuDeNavigation")]
    public virtual ICollection<TuVungChuDe> TuVungChuDe { get; set; } = new List<TuVungChuDe>();
}