// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaCong", Name = "UQ_CongThanhToan_MaCong", IsUnique = true)]
public partial class CongThanhToan
{
    [Key]
    public int MaCongThanhToan { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string MaCong { get; set; }

    [Required]
    [StringLength(128)]
    public string TenCongThanhToan { get; set; }

    [InverseProperty("MaCongThanhToanNavigation")]
    public virtual ICollection<GiaoDichThanhToan> GiaoDichThanhToan { get; set; } = new List<GiaoDichThanhToan>();
}