// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class DangKyGoiHoc
{
    [Key]
    public int MaDangKy { get; set; }

    public int MaNguoiDung { get; set; }

    public int MaGoiHoc { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal GiaDangKy { get; set; }

    public int SoNgaySuDung { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayDangKy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NgayBatDau { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NgayKetThuc { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [InverseProperty("MaDangKyNavigation")]
    public virtual ICollection<GiaoDichThanhToan> GiaoDichThanhToan { get; set; } = new List<GiaoDichThanhToan>();

    [ForeignKey("MaGoiHoc")]
    [InverseProperty("DangKyGoiHoc")]
    public virtual GoiHoc MaGoiHocNavigation { get; set; }

    [ForeignKey("MaNguoiDung")]
    [InverseProperty("DangKyGoiHoc")]
    public virtual NguoiDung MaNguoiDungNavigation { get; set; }
}