// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class DanhMucBaiGiang
{
    [Key]
    public int MaDanhMuc { get; set; }

    [Required]
    [StringLength(64)]
    public string TenDanhMuc { get; set; }

    [StringLength(512)]
    public string MoTa { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [InverseProperty("MaDanhMucNavigation")]
    public virtual ICollection<BaiGiang> BaiGiang { get; set; } = new List<BaiGiang>();
}