// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class DeThi
{
    [Key]
    public int MaDeThi { get; set; }

    [Required]
    [StringLength(128)]
    public string TenDe { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string LoaiDe { get; set; }

    public int ThoiGianLamBai { get; set; }

    public short? NamETS { get; set; }

    public int? SoDeETS { get; set; }

    public int? MaNguoiSoan { get; set; }

    public int? MaNguoiDuocGiao { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    public int? MaSinhDe { get; set; }

    [InverseProperty("MaDeThiNavigation")]
    public virtual ICollection<BuocLoTrinh> BuocLoTrinh { get; set; } = new List<BuocLoTrinh>();

    [InverseProperty("MaDeThiNavigation")]
    public virtual ICollection<CauHoiDeThi> CauHoiDeThi { get; set; } = new List<CauHoiDeThi>();

    [InverseProperty("MaDeThiNavigation")]
    public virtual ICollection<KetQuaLamBai> KetQuaLamBai { get; set; } = new List<KetQuaLamBai>();

    [ForeignKey("MaNguoiDuocGiao")]
    [InverseProperty("DeThiMaNguoiDuocGiaoNavigation")]
    public virtual NguoiDung MaNguoiDuocGiaoNavigation { get; set; }

    [ForeignKey("MaNguoiSoan")]
    [InverseProperty("DeThiMaNguoiSoanNavigation")]
    public virtual NguoiDung MaNguoiSoanNavigation { get; set; }

    [ForeignKey("MaSinhDe")]
    [InverseProperty("DeThi")]
    public virtual ThongTinSinhDe MaSinhDeNavigation { get; set; }
}