// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class GiaoDichThanhToan
{
    [Key]
    public int MaGiaoDich { get; set; }

    public int MaDangKy { get; set; }

    public int MaCongThanhToan { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal SoTien { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    public string MaGiaoDichCongThanhToan { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayTao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NgayThanhToan { get; set; }

    [ForeignKey("MaCongThanhToan")]
    [InverseProperty("GiaoDichThanhToan")]
    public virtual CongThanhToan MaCongThanhToanNavigation { get; set; }

    [ForeignKey("MaDangKy")]
    [InverseProperty("GiaoDichThanhToan")]
    public virtual DangKyGoiHoc MaDangKyNavigation { get; set; }
}