// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class GoiHoc
{
    [Key]
    public int MaGoiHoc { get; set; }

    [Required]
    [StringLength(64)]
    public string TenGoiHoc { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Gia { get; set; }

    public int SoNgaySuDung { get; set; }

    [StringLength(512)]
    public string MoTa { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayTao { get; set; }

    [InverseProperty("MaGoiHocNavigation")]
    public virtual ICollection<DangKyGoiHoc> DangKyGoiHoc { get; set; } = new List<DangKyGoiHoc>();

    [ForeignKey("MaGoiHoc")]
    [InverseProperty("MaGoiHoc")]
    public virtual ICollection<KhoaHoc> MaKhoaHoc { get; set; } = new List<KhoaHoc>();
}