// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class KetQuaPhanLopKNN
{
    [Key]
    public int MaPhanLop { get; set; }

    public int MaKetQua { get; set; }

    public byte GiaiDoanDeXuat { get; set; }

    public int? DiemMucTieu { get; set; }

    [Required]
    [StringLength(64)]
    [Unicode(false)]
    public string PhienBanMoHinh { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayPhanLop { get; set; }

    [ForeignKey("MaKetQua")]
    [InverseProperty("KetQuaPhanLopKNN")]
    public virtual KetQuaLamBai MaKetQuaNavigation { get; set; }
}