// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaKetQua", "MaDeThi", Name = "UQ_KetQuaLamBai_DeThi", IsUnique = true)]
[Index("MaLuotLam", Name = "UQ__KetQuaLa__C8728A372842CA3F", IsUnique = true)]
public partial class KetQuaLamBai
{
    [Key]
    public int MaKetQua { get; set; }

    public int MaDeThi { get; set; }

    public int MaHocVien { get; set; }

    public Guid MaLuotLam { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    public int? DiemNghe { get; set; }

    public int? DiemDoc { get; set; }

    public int? DiemTong { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayLamBai { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NgayNopBai { get; set; }

    public int? ThoiGianLamBai { get; set; }

    [InverseProperty("KetQuaLamBai")]
    public virtual ICollection<ChiTietKetQua> ChiTietKetQua { get; set; } = new List<ChiTietKetQua>();

    [InverseProperty("MaKetQuaNavigation")]
    public virtual ICollection<KetQuaPhanLopKNN> KetQuaPhanLopKNN { get; set; } = new List<KetQuaPhanLopKNN>();

    [ForeignKey("MaDeThi")]
    [InverseProperty("KetQuaLamBai")]
    public virtual DeThi MaDeThiNavigation { get; set; }

    [ForeignKey("MaHocVien")]
    [InverseProperty("KetQuaLamBai")]
    public virtual NguoiDung MaHocVienNavigation { get; set; }

    [InverseProperty("MaKetQuaNavigation")]
    public virtual ICollection<TienDoBuocLoTrinh> TienDoBuocLoTrinh { get; set; } = new List<TienDoBuocLoTrinh>();
}