// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaHocVien", "TrangThai", "NgayLamBai", Name = "IX_KetQuaLamBai_HocVienTrangThai", IsDescending = new[] { false, false, true })]
[Index("MaLuotLam", Name = "UQ__KetQuaLa__C8728A37FBEBE052", IsUnique = true)]
public partial class KetQuaLamBai
{
    [Key]
    public int MaKetQua { get; set; }

    public int? MaDeThi { get; set; }

    public int MaHocVien { get; set; }

    public Guid MaLuotLam { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    public int? DiemNghe { get; set; }

    public int? DiemDoc { get; set; }

    public int? DiemTong { get; set; }

    [Precision(3)]
    public DateTime NgayLamBai { get; set; }

    [Precision(3)]
    public DateTime? NgayNopBai { get; set; }

    public int? ThoiGianLamBai { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string LoaiBaiLam { get; set; }

    [Precision(3)]
    public DateTime? HetHanLuc { get; set; }

    public int? ThoiGianConLaiGiay { get; set; }

    [Precision(3)]
    public DateTime? BatDauPhienLuc { get; set; }

    public byte? GiaiDoanLucNop { get; set; }

    [InverseProperty("MaKetQuaNavigation")]
    public virtual ICollection<CauHoiLuotLam> CauHoiLuotLam { get; set; } = new List<CauHoiLuotLam>();

    [InverseProperty("MaKetQuaNavigation")]
    public virtual ICollection<KetQuaPhanLopKNN> KetQuaPhanLopKNN { get; set; } = new List<KetQuaPhanLopKNN>();

    [ForeignKey("MaDeThi")]
    [InverseProperty("KetQuaLamBai")]
    public virtual DeThi MaDeThiNavigation { get; set; }

    [ForeignKey("MaHocVien")]
    [InverseProperty("KetQuaLamBai")]
    public virtual NguoiDung MaHocVienNavigation { get; set; }

    [InverseProperty("MaKetQuaNavigation")]
    public virtual ICollection<NhomLuotLam> NhomLuotLam { get; set; } = new List<NhomLuotLam>();

    [InverseProperty("MaKetQuaNavigation")]
    public virtual ICollection<TienDoBuocLoTrinh> TienDoBuocLoTrinh { get; set; } = new List<TienDoBuocLoTrinh>();
}