// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("GiaiDoan", Name = "UQ__KhoaHoc__A88A4039AFA0359F", IsUnique = true)]
public partial class KhoaHoc
{
    [Key]
    public int MaKhoaHoc { get; set; }

    [Required]
    [StringLength(128)]
    public string TenKhoaHoc { get; set; }

    public byte GiaiDoan { get; set; }

    public int DiemMucTieuToiDa { get; set; }

    [StringLength(512)]
    public string MoTa { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    public int? MaAdminNoiDung { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayTao { get; set; }

    [ForeignKey("MaAdminNoiDung")]
    [InverseProperty("KhoaHoc")]
    public virtual NguoiDung MaAdminNoiDungNavigation { get; set; }

    [InverseProperty("MaKhoaHocNavigation")]
    public virtual ICollection<UnitKhoaHoc> UnitKhoaHoc { get; set; } = new List<UnitKhoaHoc>();

    [ForeignKey("MaKhoaHoc")]
    [InverseProperty("MaKhoaHoc")]
    public virtual ICollection<GoiHoc> MaGoiHoc { get; set; } = new List<GoiHoc>();
}