// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaLanLuyen", "MaChuDe", Name = "UQ_LanLuyenTuVung_ChuDe", IsUnique = true)]
public partial class LanLuyenTuVung
{
    [Key]
    public int MaLanLuyen { get; set; }

    public int MaNguoiDung { get; set; }

    public int MaChuDe { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayBatDau { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NgayNopBai { get; set; }

    [InverseProperty("LanLuyenTuVung")]
    public virtual ICollection<ChiTietLuyenTuVung> ChiTietLuyenTuVung { get; set; } = new List<ChiTietLuyenTuVung>();

    [ForeignKey("MaChuDe")]
    [InverseProperty("LanLuyenTuVung")]
    public virtual ChuDe MaChuDeNavigation { get; set; }

    [ForeignKey("MaNguoiDung")]
    [InverseProperty("LanLuyenTuVung")]
    public virtual NguoiDung MaNguoiDungNavigation { get; set; }
}