// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaUnit", "ThuTu", Name = "UQ_LessonKhoaHoc_ThuTu", IsUnique = true)]
public partial class LessonKhoaHoc
{
    [Key]
    public int MaLesson { get; set; }

    public int MaUnit { get; set; }

    [Required]
    [StringLength(128)]
    public string TenLesson { get; set; }

    [StringLength(512)]
    public string MoTa { get; set; }

    public int ThuTu { get; set; }

    [InverseProperty("MaLessonNavigation")]
    public virtual ICollection<BuocLoTrinh> BuocLoTrinh { get; set; } = new List<BuocLoTrinh>();

    [ForeignKey("MaUnit")]
    [InverseProperty("LessonKhoaHoc")]
    public virtual UnitKhoaHoc MaUnitNavigation { get; set; }
}