// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class NguLieu
{
    [Key]
    public int MaNguLieu { get; set; }

    public string NoiDungNguLieu { get; set; }

    public string NoiDungDich { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string DuongDanAudio { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string DuongDanAnh { get; set; }

    [InverseProperty("MaNguLieuNavigation")]
    public virtual ICollection<NhomCauHoi> NhomCauHoi { get; set; } = new List<NhomCauHoi>();
}