// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaNguLieu", "ThuTu", Name = "UQ_NguLieuTaiLieu_ThuTu", IsUnique = true)]
public partial class NguLieuTaiLieu
{
    [Key]
    public int MaTaiLieu { get; set; }

    public int MaNguLieu { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string LoaiTaiLieu { get; set; }

    public string NoiDung { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string DuongDanAnh { get; set; }

    public int ThuTu { get; set; }

    [ForeignKey("MaNguLieu")]
    [InverseProperty("NguLieuTaiLieu")]
    public virtual NguLieu MaNguLieuNavigation { get; set; }
}