// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("Email", Name = "UQ__NguoiDun__A9D105343E3DE794", IsUnique = true)]
public partial class NguoiDung
{
    [Key]
    public int MaNguoiDung { get; set; }

    [Required]
    [StringLength(64)]
    public string HoTen { get; set; }

    [Required]
    [StringLength(254)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(16)]
    [Unicode(false)]
    public string SoDienThoai { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string AnhDaiDien { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string VaiTro { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayTao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LanDangNhapCuoi { get; set; }

    [InverseProperty("MaAdminNoiDungNavigation")]
    public virtual ICollection<BaiGiang> BaiGiang { get; set; } = new List<BaiGiang>();

    [InverseProperty("MaNguoiDungNavigation")]
    public virtual ICollection<DangKyGoiHoc> DangKyGoiHoc { get; set; } = new List<DangKyGoiHoc>();

    [InverseProperty("MaNguoiDuocGiaoNavigation")]
    public virtual ICollection<DeThi> DeThiMaNguoiDuocGiaoNavigation { get; set; } = new List<DeThi>();

    [InverseProperty("MaNguoiSoanNavigation")]
    public virtual ICollection<DeThi> DeThiMaNguoiSoanNavigation { get; set; } = new List<DeThi>();

    [InverseProperty("MaHocVienNavigation")]
    public virtual ICollection<KetQuaLamBai> KetQuaLamBai { get; set; } = new List<KetQuaLamBai>();

    [InverseProperty("MaAdminNoiDungNavigation")]
    public virtual ICollection<KhoaHoc> KhoaHoc { get; set; } = new List<KhoaHoc>();

    [InverseProperty("MaNguoiDungNavigation")]
    public virtual ICollection<LanLuyenTuVung> LanLuyenTuVung { get; set; } = new List<LanLuyenTuVung>();

    [InverseProperty("MaNguoiDungNavigation")]
    public virtual ICollection<TienDoBuocLoTrinh> TienDoBuocLoTrinh { get; set; } = new List<TienDoBuocLoTrinh>();

    [InverseProperty("MaNguoiDungNavigation")]
    public virtual ICollection<TienDoTuVung> TienDoTuVung { get; set; } = new List<TienDoTuVung>();

    [InverseProperty("MaNguoiDungNavigation")]
    public virtual XacThucDangNhap XacThucDangNhap { get; set; }

    [InverseProperty("MaNguoiDungNavigation")]
    public virtual ICollection<XacThucOTP> XacThucOTP { get; set; } = new List<XacThucOTP>();
}