// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaNguLieu", "ThuTu", Name = "UQ_NhomCauHoi_ThuTu", IsUnique = true)]
public partial class NhomCauHoi
{
    [Key]
    public int MaCauHoi { get; set; }

    public int MaNguLieu { get; set; }

    public int ThuTu { get; set; }

    [ForeignKey("MaCauHoi")]
    [InverseProperty("NhomCauHoi")]
    public virtual CauHoi MaCauHoiNavigation { get; set; }

    [ForeignKey("MaNguLieu")]
    [InverseProperty("NhomCauHoi")]
    public virtual NguLieu MaNguLieuNavigation { get; set; }
}