// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaKetQua", "ThuTu", Name = "UQ_NhomLuotLam_ThuTu", IsUnique = true)]
public partial class NhomLuotLam
{
    [Key]
    public int MaNhomLuotLam { get; set; }

    public int MaKetQua { get; set; }

    public int? MaNguLieuGoc { get; set; }

    public int MaPart { get; set; }

    public int ThuTu { get; set; }

    public string NoiDungNguLieu { get; set; }

    public string NoiDungDich { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string DuongDanAudio { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string DuongDanAnh { get; set; }

    public string TaiLieuJson { get; set; }

    [InverseProperty("MaNhomLuotLamNavigation")]
    public virtual ICollection<CauHoiLuotLam> CauHoiLuotLam { get; set; } = new List<CauHoiLuotLam>();

    [ForeignKey("MaKetQua")]
    [InverseProperty("NhomLuotLam")]
    public virtual KetQuaLamBai MaKetQuaNavigation { get; set; }

    [ForeignKey("MaNguLieuGoc")]
    [InverseProperty("NhomLuotLam")]
    public virtual NguLieu MaNguLieuGocNavigation { get; set; }

    [ForeignKey("MaPart")]
    [InverseProperty("NhomLuotLam")]
    public virtual PartTOEIC MaPartNavigation { get; set; }
}