// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("SoPart", Name = "UQ__PartTOEI__7C5265F4AC7987BE", IsUnique = true)]
public partial class PartTOEIC
{
    [Key]
    public int MaPart { get; set; }

    public int SoPart { get; set; }

    public int SoCauChuan { get; set; }

    [InverseProperty("MaPartNavigation")]
    public virtual ICollection<BaiGiang> BaiGiang { get; set; } = new List<BaiGiang>();

    [InverseProperty("MaPartNavigation")]
    public virtual ICollection<CauHoi> CauHoi { get; set; } = new List<CauHoi>();

    [InverseProperty("MaPartNavigation")]
    public virtual ICollection<ChiTietCauHinhDeThi> ChiTietCauHinhDeThi { get; set; } = new List<ChiTietCauHinhDeThi>();
}