// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class PhanLoaiCauHoi
{
    [Key]
    public int MaPhanLoai { get; set; }

    [Required]
    [StringLength(64)]
    public string TenPhanLoai { get; set; }

    [Required]
    [StringLength(128)]
    public string MoTa { get; set; }

    [ForeignKey("MaPhanLoai")]
    [InverseProperty("MaPhanLoai")]
    public virtual ICollection<CauHoi> MaCauHoi { get; set; } = new List<CauHoi>();
}