// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaBaiGiang", "ThuTu", Name = "UQ_TaiNguyenBaiGiang_ThuTu", IsUnique = true)]
public partial class TaiNguyenBaiGiang
{
    [Key]
    public int MaTaiNguyen { get; set; }

    public int MaBaiGiang { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string LoaiTaiNguyen { get; set; }

    [Required]
    [StringLength(128)]
    public string TenTaiNguyen { get; set; }

    [Required]
    [StringLength(512)]
    [Unicode(false)]
    public string DuongDanTep { get; set; }

    public int ThuTu { get; set; }

    [ForeignKey("MaBaiGiang")]
    [InverseProperty("TaiNguyenBaiGiang")]
    public virtual BaiGiang MaBaiGiangNavigation { get; set; }
}