// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class ThongTinSinhDe
{
    [Key]
    public int MaSinhDe { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayTao { get; set; }

    [Required]
    [StringLength(64)]
    public string TenDe { get; set; }

    [InverseProperty("MaSinhDeNavigation")]
    public virtual ICollection<ChiTietCauHinhDeThi> ChiTietCauHinhDeThi { get; set; } = new List<ChiTietCauHinhDeThi>();

    [InverseProperty("MaSinhDeNavigation")]
    public virtual ICollection<DeThi> DeThi { get; set; } = new List<DeThi>();
}