// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[PrimaryKey("MaNguoiDung", "MaTuVung")]
public partial class TienDoTuVung
{
    [Key]
    public int MaNguoiDung { get; set; }

    [Key]
    public int MaTuVung { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CapNhatLuc { get; set; }

    [ForeignKey("MaNguoiDung")]
    [InverseProperty("TienDoTuVung")]
    public virtual NguoiDung MaNguoiDungNavigation { get; set; }

    [ForeignKey("MaTuVung")]
    [InverseProperty("TienDoTuVung")]
    public virtual TuVung MaTuVungNavigation { get; set; }
}