// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Keyless]
[Index("MaDangKy", "MaBuoc", Name = "UQ_TienDoBuocLoTrinh_MaDangKy_MaBuoc", IsUnique = true)]
public partial class TienDoBuocLoTrinh
{
    public int MaTienDoBLT { get; set; }

    public int MaNguoiDung { get; set; }

    public int MaBuoc { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    public byte? TyLeHoanThanh { get; set; }

    public int? MaKetQua { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CapNhatLuc { get; set; }

    public int MaDangKy { get; set; }

    [ForeignKey("MaBuoc")]
    public virtual BuocLoTrinh MaBuocNavigation { get; set; }

    [ForeignKey("MaDangKy")]
    public virtual DangKyGoiHoc MaDangKyNavigation { get; set; }

    [ForeignKey("MaKetQua")]
    public virtual KetQuaLamBai MaKetQuaNavigation { get; set; }
}