// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class ToeicDbContext : DbContext
{
    public ToeicDbContext(DbContextOptions<ToeicDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BaiGiang> BaiGiang { get; set; }

    public virtual DbSet<BuocLoTrinh> BuocLoTrinh { get; set; }

    public virtual DbSet<CauHoi> CauHoi { get; set; }

    public virtual DbSet<CauHoiDeThi> CauHoiDeThi { get; set; }

    public virtual DbSet<ChiTietCauHinhDeThi> ChiTietCauHinhDeThi { get; set; }

    public virtual DbSet<ChiTietKetQua> ChiTietKetQua { get; set; }

    public virtual DbSet<ChiTietLuyenTuVung> ChiTietLuyenTuVung { get; set; }

    public virtual DbSet<ChuDe> ChuDe { get; set; }

    public virtual DbSet<CongThanhToan> CongThanhToan { get; set; }

    public virtual DbSet<DangKyGoiHoc> DangKyGoiHoc { get; set; }

    public virtual DbSet<DanhMucBaiGiang> DanhMucBaiGiang { get; set; }

    public virtual DbSet<DeThi> DeThi { get; set; }

    public virtual DbSet<GiaoDichThanhToan> GiaoDichThanhToan { get; set; }

    public virtual DbSet<GoiHoc> GoiHoc { get; set; }

    public virtual DbSet<KetQuaLamBai> KetQuaLamBai { get; set; }

    public virtual DbSet<KetQuaPhanLopKNN> KetQuaPhanLopKNN { get; set; }

    public virtual DbSet<KhoaHoc> KhoaHoc { get; set; }

    public virtual DbSet<LanLuyenTuVung> LanLuyenTuVung { get; set; }

    public virtual DbSet<LessonKhoaHoc> LessonKhoaHoc { get; set; }

    public virtual DbSet<NguLieu> NguLieu { get; set; }

    public virtual DbSet<NguoiDung> NguoiDung { get; set; }

    public virtual DbSet<NhomCauHoi> NhomCauHoi { get; set; }

    public virtual DbSet<PartTOEIC> PartTOEIC { get; set; }

    public virtual DbSet<PhanLoaiCauHoi> PhanLoaiCauHoi { get; set; }

    public virtual DbSet<TaiNguyenBaiGiang> TaiNguyenBaiGiang { get; set; }

    public virtual DbSet<ThongTinSinhDe> ThongTinSinhDe { get; set; }

    public virtual DbSet<TienDoBuocLoTrinh> TienDoBuocLoTrinh { get; set; }

    public virtual DbSet<TienDoTuVung> TienDoTuVung { get; set; }

    public virtual DbSet<TuVung> TuVung { get; set; }

    public virtual DbSet<TuVungChuDe> TuVungChuDe { get; set; }

    public virtual DbSet<UnitKhoaHoc> UnitKhoaHoc { get; set; }

    public virtual DbSet<XacThucDangNhap> XacThucDangNhap { get; set; }

    public virtual DbSet<XacThucOTP> XacThucOTP { get; set; }

    public virtual DbSet<v_KetQuaTheoPart> v_KetQuaTheoPart { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BaiGiang>(entity =>
        {
            entity.HasKey(e => e.MaBaiGiang).HasName("PK__BaiGiang__0773C41E6E7A5305");

            entity.Property(e => e.NgayTao).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("DANG_MO");

            entity.HasOne(d => d.MaAdminNoiDungNavigation).WithMany(p => p.BaiGiang).HasConstraintName("FK__BaiGiang__MaAdmi__4D5F7D71");

            entity.HasOne(d => d.MaDanhMucNavigation).WithMany(p => p.BaiGiang).HasConstraintName("FK__BaiGiang__MaDanh__4A8310C6");

            entity.HasOne(d => d.MaPartNavigation).WithMany(p => p.BaiGiang).HasConstraintName("FK__BaiGiang__MaPart__4C6B5938");
        });

        modelBuilder.Entity<BuocLoTrinh>(entity =>
        {
            entity.HasKey(e => e.MaBuoc).HasName("PK__BuocLoTr__E4710299B22242FC");

            entity.HasOne(d => d.MaBaiGiangNavigation).WithMany(p => p.BuocLoTrinh).HasConstraintName("FK__BuocLoTri__MaBai__6EC0713C");

            entity.HasOne(d => d.MaChuDeNavigation).WithMany(p => p.BuocLoTrinh).HasConstraintName("FK__BuocLoTri__MaChu__70A8B9AE");

            entity.HasOne(d => d.MaDeThiNavigation).WithMany(p => p.BuocLoTrinh).HasConstraintName("FK__BuocLoTri__MaDeT__6FB49575");

            entity.HasOne(d => d.MaLessonNavigation).WithMany(p => p.BuocLoTrinh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BuocLoTri__MaLes__6CD828CA");
        });

        modelBuilder.Entity<CauHoi>(entity =>
        {
            entity.HasKey(e => e.MaCauHoi).HasName("PK__CauHoi__1937D77BB8F81F1C");

            entity.Property(e => e.PhuongAnDung).IsFixedLength();

            entity.HasOne(d => d.MaPartNavigation).WithMany(p => p.CauHoi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CauHoi__MaPart__02084FDA");

            entity.HasMany(d => d.MaPhanLoai).WithMany(p => p.MaCauHoi)
                .UsingEntity<Dictionary<string, object>>(
                    "ChiTietPhanLoai",
                    r => r.HasOne<PhanLoaiCauHoi>().WithMany()
                        .HasForeignKey("MaPhanLoai")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ChiTietPh__MaPha__0F624AF8"),
                    l => l.HasOne<CauHoi>().WithMany()
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ChiTietPh__MaCau__0E6E26BF"),
                    j =>
                    {
                        j.HasKey("MaCauHoi", "MaPhanLoai").HasName("pk_ChiTietPhanLoai");
                    });
        });

        modelBuilder.Entity<CauHoiDeThi>(entity =>
        {
            entity.HasOne(d => d.MaCauHoiNavigation).WithMany(p => p.CauHoiDeThi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CauHoiDeT__MaCau__282DF8C2");

            entity.HasOne(d => d.MaDeThiNavigation).WithMany(p => p.CauHoiDeThi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CauHoiDeT__MaDeT__2739D489");
        });

        modelBuilder.Entity<ChiTietCauHinhDeThi>(entity =>
        {
            entity.HasOne(d => d.MaPartNavigation).WithMany(p => p.ChiTietCauHinhDeThi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ChiTietCa__MaPar__160F4887");

            entity.HasOne(d => d.MaSinhDeNavigation).WithMany(p => p.ChiTietCauHinhDeThi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ChiTietCa__MaSin__151B244E");
        });

        modelBuilder.Entity<ChiTietKetQua>(entity =>
        {
            entity.Property(e => e.DapAnChon).IsFixedLength();

            entity.HasOne(d => d.CauHoiDeThi).WithMany(p => p.ChiTietKetQua)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChiTietKetQua_CauHoiDeThi");

            entity.HasOne(d => d.KetQuaLamBai).WithMany(p => p.ChiTietKetQua)
                .HasPrincipalKey(p => new { p.MaKetQua, p.MaDeThi })
                .HasForeignKey(d => new { d.MaKetQua, d.MaDeThi })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChiTietKetQua_KetQua");
        });

        modelBuilder.Entity<ChiTietLuyenTuVung>(entity =>
        {
            entity.Property(e => e.DapAnChon).IsFixedLength();
            entity.Property(e => e.PhuongAnDung).IsFixedLength();

            entity.HasOne(d => d.TuVungChuDe).WithMany(p => p.ChiTietLuyenTuVung)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChiTietLuyenTuVung_Tu");

            entity.HasOne(d => d.LanLuyenTuVung).WithMany(p => p.ChiTietLuyenTuVung)
                .HasPrincipalKey(p => new { p.MaLanLuyen, p.MaChuDe })
                .HasForeignKey(d => new { d.MaLanLuyen, d.MaChuDe })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChiTietLuyenTuVung_Lan");
        });

        modelBuilder.Entity<ChuDe>(entity =>
        {
            entity.HasKey(e => e.MaChuDe).HasName("PK__ChuDe__358545114865C776");

            entity.Property(e => e.TrangThai).HasDefaultValue("DANG_MO");
        });

        modelBuilder.Entity<CongThanhToan>(entity =>
        {
            entity.HasKey(e => e.MaCongThanhToan).HasName("PK__CongThan__CA2CF790BD8C7F85");
        });

        modelBuilder.Entity<DangKyGoiHoc>(entity =>
        {
            entity.HasKey(e => e.MaDangKy).HasName("PK__DangKyGo__BA90F02D43857556");

            entity.Property(e => e.NgayDangKy).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("CHO_THANH_TOAN");

            entity.HasOne(d => d.MaGoiHocNavigation).WithMany(p => p.DangKyGoiHoc)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DangKyGoi__MaGoi__6383C8BA");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.DangKyGoiHoc)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DangKyGoi__MaNgu__628FA481");
        });

        modelBuilder.Entity<DanhMucBaiGiang>(entity =>
        {
            entity.HasKey(e => e.MaDanhMuc).HasName("PK__DanhMucB__B3750887F0AAE3DC");

            entity.Property(e => e.TrangThai).HasDefaultValue("DANG_MO");
        });

        modelBuilder.Entity<DeThi>(entity =>
        {
            entity.HasKey(e => e.MaDeThi).HasName("PK__DeThi__9F9645B09025752B");

            entity.Property(e => e.TrangThai).HasDefaultValue("CLOSE");

            entity.HasOne(d => d.MaNguoiDuocGiaoNavigation).WithMany(p => p.DeThiMaNguoiDuocGiaoNavigation).HasConstraintName("FK__DeThi__MaNguoiDu__1F98B2C1");

            entity.HasOne(d => d.MaNguoiSoanNavigation).WithMany(p => p.DeThiMaNguoiSoanNavigation).HasConstraintName("FK__DeThi__MaNguoiSo__1EA48E88");

            entity.HasOne(d => d.MaSinhDeNavigation).WithMany(p => p.DeThi).HasConstraintName("FK__DeThi__MaSinhDe__22751F6C");
        });

        modelBuilder.Entity<GiaoDichThanhToan>(entity =>
        {
            entity.HasKey(e => e.MaGiaoDich).HasName("PK__GiaoDich__0A2A24EB443D3AA8");

            entity.HasIndex(e => new { e.MaCongThanhToan, e.MaGiaoDichCongThanhToan }, "UX_GiaoDichThanhToan_MaCong")
                .IsUnique()
                .HasFilter("([MaGiaoDichCongThanhToan] IS NOT NULL)");

            entity.Property(e => e.NgayTao).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("CHO_XU_LY");

            entity.HasOne(d => d.MaCongThanhToanNavigation).WithMany(p => p.GiaoDichThanhToan)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GiaoDichT__MaCon__71D1E811");

            entity.HasOne(d => d.MaDangKyNavigation).WithMany(p => p.GiaoDichThanhToan)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GiaoDichT__MaDan__70DDC3D8");
        });

        modelBuilder.Entity<GoiHoc>(entity =>
        {
            entity.HasKey(e => e.MaGoiHoc).HasName("PK__GoiHoc__9A2D648F7827E1A0");

            entity.Property(e => e.NgayTao).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("DANG_MO");

            entity.HasMany(d => d.MaKhoaHoc).WithMany(p => p.MaGoiHoc)
                .UsingEntity<Dictionary<string, object>>(
                    "GoiHocKhoaHoc",
                    r => r.HasOne<KhoaHoc>().WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__GoiHocKho__MaKho__5FB337D6"),
                    l => l.HasOne<GoiHoc>().WithMany()
                        .HasForeignKey("MaGoiHoc")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__GoiHocKho__MaGoi__5EBF139D"),
                    j =>
                    {
                        j.HasKey("MaGoiHoc", "MaKhoaHoc");
                    });
        });

        modelBuilder.Entity<KetQuaLamBai>(entity =>
        {
            entity.HasKey(e => e.MaKetQua).HasName("PK__KetQuaLa__D5B3102A29BD01CD");

            entity.Property(e => e.DiemTong).HasComputedColumnSql("([DiemNghe]+[DiemDoc])", false);
            entity.Property(e => e.MaLuotLam).HasDefaultValueSql("(newid())");
            entity.Property(e => e.NgayLamBai).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("DANG_LAM");

            entity.HasOne(d => d.MaDeThiNavigation).WithMany(p => p.KetQuaLamBai)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__KetQuaLam__MaDeT__2DE6D218");

            entity.HasOne(d => d.MaHocVienNavigation).WithMany(p => p.KetQuaLamBai)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__KetQuaLam__MaHoc__2EDAF651");
        });

        modelBuilder.Entity<KetQuaPhanLopKNN>(entity =>
        {
            entity.HasKey(e => e.MaPhanLop).HasName("PK__KetQuaPh__375CC59153802B91");

            entity.Property(e => e.NgayPhanLop).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.MaKetQuaNavigation).WithMany(p => p.KetQuaPhanLopKNN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__KetQuaPha__MaKet__40058253");
        });

        modelBuilder.Entity<KhoaHoc>(entity =>
        {
            entity.HasKey(e => e.MaKhoaHoc).HasName("PK__KhoaHoc__48F0FF98ABB2606A");

            entity.Property(e => e.NgayTao).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("DANG_MO");

            entity.HasOne(d => d.MaAdminNoiDungNavigation).WithMany(p => p.KhoaHoc).HasConstraintName("FK__KhoaHoc__MaAdmin__5441852A");
        });

        modelBuilder.Entity<LanLuyenTuVung>(entity =>
        {
            entity.HasKey(e => e.MaLanLuyen).HasName("PK__LanLuyen__32A13F87AA217346");

            entity.Property(e => e.NgayBatDau).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("DANG_LAM");

            entity.HasOne(d => d.MaChuDeNavigation).WithMany(p => p.LanLuyenTuVung)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LanLuyenT__MaChu__0697FACD");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.LanLuyenTuVung)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LanLuyenT__MaNgu__05A3D694");
        });

        modelBuilder.Entity<LessonKhoaHoc>(entity =>
        {
            entity.HasKey(e => e.MaLesson).HasName("PK__LessonKh__65796D6AD1BA69D4");

            entity.HasOne(d => d.MaUnitNavigation).WithMany(p => p.LessonKhoaHoc)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LessonKho__MaUni__681373AD");
        });

        modelBuilder.Entity<NguLieu>(entity =>
        {
            entity.HasKey(e => e.MaNguLieu).HasName("PK__NguLieu__D50B33012A252B5C");
        });

        modelBuilder.Entity<NguoiDung>(entity =>
        {
            entity.HasKey(e => e.MaNguoiDung).HasName("PK__NguoiDun__C539D762BA831925");

            entity.Property(e => e.NgayTao).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("CHO_XAC_THUC");
            entity.Property(e => e.VaiTro).HasDefaultValue("HOC_VIEN");
        });

        modelBuilder.Entity<NhomCauHoi>(entity =>
        {
            entity.HasKey(e => e.MaCauHoi).HasName("PK__NhomCauH__1937D77B1ABBA907");

            entity.Property(e => e.MaCauHoi).ValueGeneratedNever();

            entity.HasOne(d => d.MaCauHoiNavigation).WithOne(p => p.NhomCauHoi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NhomCauHo__MaCau__07C12930");

            entity.HasOne(d => d.MaNguLieuNavigation).WithMany(p => p.NhomCauHoi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NhomCauHo__MaNgu__08B54D69");
        });

        modelBuilder.Entity<PartTOEIC>(entity =>
        {
            entity.HasKey(e => e.MaPart).HasName("PK__PartTOEI__4CF160AD8F6E188E");
        });

        modelBuilder.Entity<PhanLoaiCauHoi>(entity =>
        {
            entity.HasKey(e => e.MaPhanLoai).HasName("PK__PhanLoai__E8C0182EFBE4AE20");
        });

        modelBuilder.Entity<TaiNguyenBaiGiang>(entity =>
        {
            entity.HasKey(e => e.MaTaiNguyen).HasName("PK__TaiNguye__63D831DE2CAB40C5");

            entity.HasOne(d => d.MaBaiGiangNavigation).WithMany(p => p.TaiNguyenBaiGiang)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TaiNguyen__MaBai__540C7B00");
        });

        modelBuilder.Entity<ThongTinSinhDe>(entity =>
        {
            entity.HasKey(e => e.MaSinhDe).HasName("PK__ThongTin__00C99D87F2B0C555");

            entity.Property(e => e.NgayTao).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<TienDoBuocLoTrinh>(entity =>
        {
            entity.HasKey(e => e.MaTienDoBLT).HasName("PK__TienDoBu__09A45B6A28836F9E");

            entity.Property(e => e.CapNhatLuc).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("CHUA_LAM");

            entity.HasOne(d => d.MaBuocNavigation).WithMany(p => p.TienDoBuocLoTrinh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TienDoBuo__MaBuo__76619304");

            entity.HasOne(d => d.MaKetQuaNavigation).WithMany(p => p.TienDoBuocLoTrinh).HasConstraintName("FK__TienDoBuo__MaKet__7A3223E8");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.TienDoBuocLoTrinh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TienDoBuo__MaNgu__756D6ECB");
        });

        modelBuilder.Entity<TienDoTuVung>(entity =>
        {
            entity.Property(e => e.CapNhatLuc).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TrangThai).HasDefaultValue("DANG_HOC");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.TienDoTuVung)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TienDoTuV__MaNgu__7E02B4CC");

            entity.HasOne(d => d.MaTuVungNavigation).WithMany(p => p.TienDoTuVung)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TienDoTuV__MaTuV__7EF6D905");
        });

        modelBuilder.Entity<TuVung>(entity =>
        {
            entity.HasKey(e => e.MaTuVung).HasName("PK__TuVung__BB64F7A9DA5881C4");
        });

        modelBuilder.Entity<TuVungChuDe>(entity =>
        {
            entity.HasKey(e => new { e.MaChuDe, e.MaTuVung }).HasName("pk_TuVungChuDe");

            entity.HasOne(d => d.MaChuDeNavigation).WithMany(p => p.TuVungChuDe)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TuVungChu__MaChu__5F7E2DAC");

            entity.HasOne(d => d.MaTuVungNavigation).WithMany(p => p.TuVungChuDe)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TuVungChu__MaTuV__5E8A0973");
        });

        modelBuilder.Entity<UnitKhoaHoc>(entity =>
        {
            entity.HasKey(e => e.MaUnit).HasName("PK__UnitKhoa__64CE11274BC3C74F");

            entity.HasOne(d => d.MaKhoaHocNavigation).WithMany(p => p.UnitKhoaHoc)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UnitKhoaH__MaKho__634EBE90");
        });

        modelBuilder.Entity<XacThucDangNhap>(entity =>
        {
            entity.HasKey(e => e.MaXacThuc).HasName("PK__XacThucD__71196B3C13DCEE47");

            entity.HasIndex(e => e.GoogleId, "UX_XacThucDangNhap_GoogleId")
                .IsUnique()
                .HasFilter("([GoogleId] IS NOT NULL)");

            entity.Property(e => e.TaoLuc).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithOne(p => p.XacThucDangNhap)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__XacThucDa__MaNgu__412EB0B6");
        });

        modelBuilder.Entity<XacThucOTP>(entity =>
        {
            entity.HasKey(e => e.MaXacThuc).HasName("PK__XacThucO__71196B3CAF97A937");

            entity.Property(e => e.NgayTao).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ThoiGianHetHan).HasDefaultValueSql("(dateadd(minute,(15),getdate()))");
            entity.Property(e => e.TrangThai).HasDefaultValue("CHUA_XAC_THUC");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.XacThucOTP)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__XacThucOT__MaNgu__46E78A0C");
        });

        modelBuilder.Entity<v_KetQuaTheoPart>(entity =>
        {
            entity.ToView("v_KetQuaTheoPart");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}