// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class TuVung
{
    [Key]
    public int MaTuVung { get; set; }

    [Required]
    [Column("TuVung")]
    [StringLength(128)]
    public string TuVung1 { get; set; }

    [Required]
    [StringLength(256)]
    public string Nghia { get; set; }

    [StringLength(128)]
    public string PhienAm { get; set; }

    [StringLength(512)]
    public string ViDu { get; set; }

    [StringLength(512)]
    public string DichViDu { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string DuongDanAudio { get; set; }

    [InverseProperty("MaTuVungNavigation")]
    public virtual ICollection<TienDoTuVung> TienDoTuVung { get; set; } = new List<TienDoTuVung>();

    [InverseProperty("MaTuVungNavigation")]
    public virtual ICollection<TuVungChuDe> TuVungChuDe { get; set; } = new List<TuVungChuDe>();
}