// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[PrimaryKey("MaChuDe", "MaTuVung")]
public partial class TuVungChuDe
{
    [Key]
    public int MaTuVung { get; set; }

    [Key]
    public int MaChuDe { get; set; }

    [InverseProperty("TuVungChuDe")]
    public virtual ICollection<ChiTietLuyenTuVung> ChiTietLuyenTuVung { get; set; } = new List<ChiTietLuyenTuVung>();

    [ForeignKey("MaChuDe")]
    [InverseProperty("TuVungChuDe")]
    public virtual ChuDe MaChuDeNavigation { get; set; }

    [ForeignKey("MaTuVung")]
    [InverseProperty("TuVungChuDe")]
    public virtual TuVung MaTuVungNavigation { get; set; }
}