// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaKhoaHoc", "ThuTu", Name = "UQ_UnitKhoaHoc_ThuTu", IsUnique = true)]
public partial class UnitKhoaHoc
{
    [Key]
    public int MaUnit { get; set; }

    public int MaKhoaHoc { get; set; }

    [Required]
    [StringLength(128)]
    public string TenUnit { get; set; }

    [StringLength(512)]
    public string MoTa { get; set; }

    public int ThuTu { get; set; }

    [InverseProperty("MaUnitNavigation")]
    public virtual ICollection<LessonKhoaHoc> LessonKhoaHoc { get; set; } = new List<LessonKhoaHoc>();

    [ForeignKey("MaKhoaHoc")]
    [InverseProperty("UnitKhoaHoc")]
    public virtual KhoaHoc MaKhoaHocNavigation { get; set; }
}