// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Keyless]
public partial class v_KetQuaTheoPart
{
    public int MaKetQua { get; set; }

    public int SoPart { get; set; }

    public int? TongSoCau { get; set; }

    public int? SoCauDung { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? DiemPhanTram { get; set; }
}