// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

public partial class XacThucOTP
{
    [Key]
    public int MaXacThuc { get; set; }

    public int MaNguoiDung { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string MaOTP { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ThoiGianHetHan { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string TrangThai { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayTao { get; set; }

    [ForeignKey("MaNguoiDung")]
    [InverseProperty("XacThucOTP")]
    public virtual NguoiDung MaNguoiDungNavigation { get; set; }
}