// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STO123.Models;

[Index("MaNguoiDung", Name = "UQ__XacThucD__C539D76379CFE222", IsUnique = true)]
public partial class XacThucDangNhap
{
    [Key]
    public int MaXacThuc { get; set; }

    public int MaNguoiDung { get; set; }

    [Required]
    [StringLength(16)]
    [Unicode(false)]
    public string LoaiXacThuc { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string MatKhauMaHoa { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string GoogleId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TaoLuc { get; set; }

    [ForeignKey("MaNguoiDung")]
    [InverseProperty("XacThucDangNhap")]
    public virtual NguoiDung MaNguoiDungNavigation { get; set; }
}